# Generated by Django 5.0.7 on 2024-08-06 17:27

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=250)),
                ("job_title", models.CharField(blank=True, max_length=250)),
                ("location", models.CharField(blank=True, max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("website_url", models.URLField()),
                ("logo", models.ImageField(blank=True, upload_to="company-logo")),
                ("description", models.TextField(blank=True)),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "company_name"],
                "indexes": [
                    models.Index(
                        fields=["-created", "company_name"],
                        name="listings_li_created_23f43c_idx",
                    )
                ],
            },
        ),
    ]
